# Generated by Django 3.2.7 on 2021-10-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jists', '0004_auto_20211008_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='jist',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
